# Generated by Django 6.0.7 on 2026-07-21 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_camion', models.CharField(choices=[('CITERNE', 'Camion citerne'), ('BENNE', 'Camion benne'), ('PLATEAU', 'Camion plateau'), ('CONTENEUR', 'Porte conteneur'), ('PORTE_ENGIN', 'Porte engin')], max_length=50)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('modele', models.CharField(blank=True, max_length=100, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('capacite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite_capacite', models.CharField(default='litres', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='camions/')),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
