# Generated by Django 6.0.7 on 2026-07-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='photo',
        ),
        migrations.CreateModel(
            name='ImageCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camions/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.camion')),
            ],
        ),
    ]
