# Generated by Django 6.0.7 on 2026-07-21 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_camion_photo_imagecamion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_camion', models.CharField(choices=[('CITERNE', 'Camion citerne'), ('BENNE', 'Camion benne'), ('PLATEAU', 'Camion plateau'), ('CONTENEUR', 'Porte conteneur'), ('PORTE_ENGIN', 'Porte engin')], max_length=50)),
                ('nombre_camions', models.PositiveIntegerField(default=1)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité à transporter', max_digits=10)),
                ('unite', models.CharField(default='litres', max_length=20)),
                ('date_chargement', models.DateField()),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_transport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
