# Generated by Django 6.0.7 on 2026-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='ville',
            field=models.CharField(default='Bamako', max_length=100),
        ),
    ]
