# Generated by Django 6.0.7 on 2026-07-21 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_camion_latitude_camion_longitude_camion_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='camion',
        ),
        migrations.AddField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='missions_client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='transporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_transporteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_permis', models.CharField(max_length=50)),
                ('date_expiration_permis', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chauffeurs/')),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='PREVU', max_length=20)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chauffeur')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camions', to='core.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delai_depart', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('valide_jusquau', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='core.demandetransport')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='proposition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='core.proposition'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PropositionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chauffeur')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camions', to='core.proposition')),
            ],
            options={
                'unique_together': {('proposition', 'camion')},
            },
        ),
    ]
