# Generated by Django 6.0.7 on 2026-07-22 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_mission_camion_mission_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=30, null=True)),
                ('nouveau_statut', models.CharField(max_length=30)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('batterie', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('vitesse', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='missioncamion',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='code_acces',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='missioncamion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='missioncamion',
            name='heure_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missioncamion',
            name='heure_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missioncamion',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missioncamion',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='missioncamion',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.camion'),
        ),
        migrations.AlterField(
            model_name='missioncamion',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='core.chauffeur'),
        ),
        migrations.AlterField(
            model_name='missioncamion',
            name='statut',
            field=models.CharField(choices=[('PREVU', 'Prévu'), ('AU_CHARGEMENT', 'Au chargement'), ('CHARGE', 'Chargé'), ('EN_ROUTE', 'En route'), ('ARRIVE', 'Arrivé'), ('LIVRE', 'Livré'), ('PANNE', 'En panne'), ('ANNULE', 'Annulé')], default='PREVU', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='missioncamion',
            constraint=models.UniqueConstraint(fields=('mission', 'camion'), name='unique_camion_par_mission'),
        ),
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.UniqueConstraint(fields=('demande', 'transporteur'), name='unique_proposition_transporteur_par_demande'),
        ),
        migrations.AddField(
            model_name='historiquemission',
            name='mission_camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='core.missioncamion'),
        ),
        migrations.AddField(
            model_name='positiongps',
            name='mission_camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.missioncamion'),
        ),
    ]
