# Generated by Django 6.0.7 on 2026-08-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historiquemission_positiongps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='mission',
            name='date_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
