# Generated by Django 6.0.7 on 2026-08-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mission_options_mission_date_arrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='mode_suivi',
            field=models.CharField(choices=[('GPS', 'GPS'), ('TELEPHONE', 'Téléphone')], default='GPS', max_length=20),
        ),
        migrations.AddField(
            model_name='camion',
            name='suivi_par_telephone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positiongps',
            name='source',
            field=models.CharField(choices=[('GPS', 'GPS'), ('TELEPHONE', 'Téléphone')], default='GPS', max_length=20),
        ),
        migrations.AddField(
            model_name='positiongps',
            name='telephone_chauffeur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
