# Generated by Django 6.0.7 on 2026-08-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_camion_mode_suivi_camion_suivi_par_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandetransport',
            name='latitude_arrivee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='demandetransport',
            name='latitude_depart',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='demandetransport',
            name='longitude_arrivee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='demandetransport',
            name='longitude_depart',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='demandetransport',
            name='pays_arrivee',
            field=models.CharField(default='Mali', max_length=100),
        ),
        migrations.AddField(
            model_name='demandetransport',
            name='pays_depart',
            field=models.CharField(default='Mali', max_length=100),
        ),
        migrations.AddField(
            model_name='proposition',
            name='distance_estimee_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='score_matching',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score de matching pour le tri des propositions', max_digits=5),
        ),
    ]
