# Generated by Django 6.0.7 on 2026-08-09 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_demandetransport_international_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.camion')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.chauffeur')),
            ],
            options={
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('camion',), name='unique_affectation_active_par_camion'), models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('chauffeur',), name='unique_affectation_active_par_chauffeur')],
            },
        ),
    ]
