# Generated by Django 6.0.7 on 2026-08-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_affectationchauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='position_updated_at',
            field=models.DateTimeField(blank=True, help_text="Date de la dernière position réellement rapportée (distingue une valeur statique jamais rafraîchie d'une vraie remontée GPS).", null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='position_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
