# Generated by Django 6.0.7 on 2026-08-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_camion_position_updated_at_chauffeur_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecamion',
            name='principale',
            field=models.BooleanField(default=False),
        ),
    ]
