# Generated by Django 6.0.7 on 2026-08-11 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_imagecamion_principale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('NOUVELLE_DEMANDE', 'Nouvelle demande'), ('NOUVELLE_PROPOSITION', 'Nouvelle proposition'), ('PROPOSITION_ACCEPTEE', 'Proposition acceptée'), ('PROPOSITION_REFUSEE', 'Proposition refusée'), ('MISSION_CREEE', 'Mission créée'), ('MISSION_DEMARREE', 'Mission démarrée'), ('MISSION_TERMINEE', 'Mission terminée')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
