# Generated by Django 6.0.7 on 2026-08-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
