# Generated by Django 6.0.7 on 2026-08-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pays_devise_cedeao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='pays',
            field=models.CharField(choices=[('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('CV', 'Cap-Vert'), ('CI', "Côte d'Ivoire"), ('GM', 'Gambie'), ('GH', 'Ghana'), ('GN', 'Guinée'), ('GW', 'Guinée-Bissau'), ('LR', 'Liberia'), ('ML', 'Mali'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('SN', 'Sénégal'), ('SL', 'Sierra Leone'), ('TG', 'Togo')], default='ML', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(choices=[('BJ', 'Bénin'), ('BF', 'Burkina Faso'), ('CV', 'Cap-Vert'), ('CI', "Côte d'Ivoire"), ('GM', 'Gambie'), ('GH', 'Ghana'), ('GN', 'Guinée'), ('GW', 'Guinée-Bissau'), ('LR', 'Liberia'), ('ML', 'Mali'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('SN', 'Sénégal'), ('SL', 'Sierra Leone'), ('TG', 'Togo')], default='ML', max_length=2),
        ),
    ]
