# Generated by Django 6.0.7 on 2026-08-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_reinitialisation',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='code_reinitialisation_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
