# Generated by Django 6.0.7 on 2026-08-20 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_code_reinitialisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.proposition'),
        ),
    ]
