# Generated by Django 6.0.7 on 2026-08-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification_proposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOUVELLE_DEMANDE', 'Nouvelle demande'), ('NOUVELLE_PROPOSITION', 'Nouvelle proposition'), ('PROPOSITION_ACCEPTEE', 'Proposition acceptée'), ('PROPOSITION_REFUSEE', 'Proposition refusée'), ('MISSION_CREEE', 'Mission créée'), ('MISSION_DEMARREE', 'Mission démarrée'), ('MISSION_TERMINEE', 'Mission terminée'), ('MISSION_ANNULEE', 'Mission annulée')], max_length=30),
        ),
    ]
