# Generated by Django 6.0.7 on 2026-08-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_corriger_unite_capacite_camions'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='essieux',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre d'essieux du camion.", null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='format_autre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='camion',
            name='format_camion',
            field=models.CharField(blank=True, choices=[('20_PIEDS', '20 pieds'), ('40_PIEDS', '40 pieds'), ('20_40_PIEDS', '20/40 pieds'), ('45_PIEDS', '45 pieds'), ('CITERNE_5000L', '5 000 L'), ('CITERNE_10000L', '10 000 L'), ('CITERNE_15000L', '15 000 L'), ('CITERNE_20000L', '20 000 L'), ('CITERNE_25000L', '25 000 L'), ('CITERNE_30000L', '30 000 L'), ('CITERNE_40000L', '40 000 L'), ('AUTRE', 'Autre')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='demandetransport',
            name='format_autre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='demandetransport',
            name='format_camion',
            field=models.CharField(blank=True, choices=[('20_PIEDS', '20 pieds'), ('40_PIEDS', '40 pieds'), ('20_40_PIEDS', '20/40 pieds'), ('45_PIEDS', '45 pieds'), ('CITERNE_5000L', '5 000 L'), ('CITERNE_10000L', '10 000 L'), ('CITERNE_15000L', '15 000 L'), ('CITERNE_20000L', '20 000 L'), ('CITERNE_25000L', '25 000 L'), ('CITERNE_30000L', '30 000 L'), ('CITERNE_40000L', '40 000 L'), ('AUTRE', 'Autre')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='camion',
            name='type_camion',
            field=models.CharField(choices=[('CITERNE', 'Camion citerne'), ('BENNE', 'Camion benne'), ('PLATEAU', 'Camion plateau'), ('CONTENEUR', 'Porte-conteneur'), ('PORTE_ENGIN', 'Porte-engin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='demandetransport',
            name='type_camion',
            field=models.CharField(choices=[('CITERNE', 'Camion citerne'), ('BENNE', 'Camion benne'), ('PLATEAU', 'Camion plateau'), ('CONTENEUR', 'Porte-conteneur'), ('PORTE_ENGIN', 'Porte-engin')], max_length=50),
        ),
    ]
