# Generated by Django 6.0.7 on 2026-08-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_camion_essieux_camion_format_autre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='format_camion',
            field=models.CharField(blank=True, choices=[('20_PIEDS', '20 pieds'), ('40_PIEDS', '40 pieds'), ('20_40_PIEDS', '20/40 pieds'), ('45_PIEDS', '45 pieds'), ('CITERNE_15000L', '15 000 L'), ('CITERNE_20000L', '20 000 L'), ('CITERNE_25000L', '25 000 L'), ('CITERNE_38000L', '38 000 L'), ('CITERNE_40000L', '40 000 L'), ('CITERNE_45000L', '45 000 L'), ('CITERNE_55000L', '55 000 L'), ('AUTRE', 'Autre')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='demandetransport',
            name='format_camion',
            field=models.CharField(blank=True, choices=[('20_PIEDS', '20 pieds'), ('40_PIEDS', '40 pieds'), ('20_40_PIEDS', '20/40 pieds'), ('45_PIEDS', '45 pieds'), ('CITERNE_15000L', '15 000 L'), ('CITERNE_20000L', '20 000 L'), ('CITERNE_25000L', '25 000 L'), ('CITERNE_38000L', '38 000 L'), ('CITERNE_40000L', '40 000 L'), ('CITERNE_45000L', '45 000 L'), ('CITERNE_55000L', '55 000 L'), ('AUTRE', 'Autre')], default='', max_length=30),
        ),
    ]
