# Generated by Django 6.0.7 on 2026-08-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_camion_format_camion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='format_camion',
            field=models.CharField(blank=True, choices=[('20_PIEDS', '20 pieds'), ('40_PIEDS', '40 pieds'), ('20_40_PIEDS', '20/40 pieds'), ('45_PIEDS', '45 pieds'), ('CITERNE_10000L', '10 000 L'), ('CITERNE_15000L', '15 000 L'), ('CITERNE_20000L', '20 000 L'), ('CITERNE_25000L', '25 000 L'), ('CITERNE_30000L', '30 000 L'), ('CITERNE_35000L', '35 000 L'), ('CITERNE_40000L', '40 000 L'), ('CITERNE_43000L', '43 000 L'), ('CITERNE_45000L', '45 000 L'), ('CITERNE_50000L', '50 000 L'), ('BENNE_4X2', '4×2 — 6 roues'), ('BENNE_6X4', '6×4 — 10 roues'), ('BENNE_8X4', '8×4 — 12 roues'), ('AUTRE', 'Autre')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='demandetransport',
            name='format_camion',
            field=models.CharField(blank=True, choices=[('20_PIEDS', '20 pieds'), ('40_PIEDS', '40 pieds'), ('20_40_PIEDS', '20/40 pieds'), ('45_PIEDS', '45 pieds'), ('CITERNE_10000L', '10 000 L'), ('CITERNE_15000L', '15 000 L'), ('CITERNE_20000L', '20 000 L'), ('CITERNE_25000L', '25 000 L'), ('CITERNE_30000L', '30 000 L'), ('CITERNE_35000L', '35 000 L'), ('CITERNE_40000L', '40 000 L'), ('CITERNE_43000L', '43 000 L'), ('CITERNE_45000L', '45 000 L'), ('CITERNE_50000L', '50 000 L'), ('BENNE_4X2', '4×2 — 6 roues'), ('BENNE_6X4', '6×4 — 10 roues'), ('BENNE_8X4', '8×4 — 12 roues'), ('AUTRE', 'Autre')], default='', max_length=30),
        ),
    ]
