# Generated by Django 6.0.7 on 2026-08-31 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_camion_format_camion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('NOUVELLE_DEMANDE', 'Nouvelle demande'), ('NOUVELLE_PROPOSITION', 'Nouvelle proposition'), ('PROPOSITION_ACCEPTEE', 'Proposition acceptée'), ('PROPOSITION_REFUSEE', 'Proposition refusée'), ('MISSION_CREEE', 'Mission créée'), ('MISSION_DEMARREE', 'Mission démarrée'), ('MISSION_TERMINEE', 'Mission terminée'), ('MISSION_ANNULEE', 'Mission annulée'), ('PAIEMENT_ENCAISSE', 'Paiement encaissé'), ('PAIEMENT_SECURISE', 'Paiement sécurisé'), ('PAIEMENT_LIBERE', 'Paiement libéré'), ('PAIEMENT_VERSE', 'Paiement versé'), ('PAIEMENT_REMBOURSE', 'Paiement remboursé'), ('PAIEMENT_ECHEC', 'Échec du paiement'), ('LITIGE_OUVERT', 'Litige ouvert'), ('LITIGE_RESOLU', 'Litige résolu')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_compte',
            field=models.CharField(choices=[('TRANSPORTEUR', 'Transporteur'), ('ENTREPRISE', 'Entreprise'), ('ADMIN', 'Administrateur'), ('AGENT', 'Agent AfriFlotte')], default='TRANSPORTEUR', max_length=20),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CARTE', 'Carte bancaire'), ('MANUEL', 'Manuel (main à main)')], max_length=10)),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Copie de mission.prix_final au moment de la création — ligne financière figée.', max_digits=12)),
                ('devise', models.CharField(help_text='Copie figée de devise_pour_pays(mission.demande.pays_depart) au moment de la création.', max_length=3)),
                ('commission_taux', models.DecimalField(decimal_places=2, help_text='Taux de commission AfriFlotte (%) au moment de la création, ex. 5.00.', max_digits=5)),
                ('commission_montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_transporteur', models.DecimalField(decimal_places=2, help_text='montant_total - commission_montant, dû au transporteur.', max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENCAISSE', 'Encaissé'), ('SECURISE', 'Sécurisé'), ('LIBERE', 'Libéré'), ('VERSE', 'Versé au transporteur'), ('REMBOURSE', 'Remboursé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('reference_externe', models.CharField(blank=True, default='', help_text='Référence de transaction PSP (CARTE) ou référence/reçu manuel (MANUEL).', max_length=100)),
                ('litige_en_cours', models.BooleanField(default=False)),
                ('motif_remboursement', models.TextField(blank=True, default='')),
                ('date_encaissement', models.DateTimeField(blank=True, null=True)),
                ('date_securisation', models.DateTimeField(blank=True, null=True)),
                ('date_liberation', models.DateTimeField(blank=True, null=True)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
                ('date_remboursement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaisses', to=settings.AUTH_USER_MODEL)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='core.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXAMEN', 'En examen'), ('RESOLU_CLIENT', 'Résolu en faveur du client'), ('RESOLU_TRANSPORTEUR', 'Résolu en faveur du transporteur'), ('REJETE', 'Rejeté')], default='OUVERT', max_length=20)),
                ('resolution_commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolu_at', models.DateTimeField(blank=True, null=True)),
                ('ouvert_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_ouverts', to=settings.AUTH_USER_MODEL)),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_resolus', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='core.paiement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.paiement'),
        ),
        migrations.CreateModel(
            name='PreuvePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.ImageField(upload_to='preuves_paiement/')),
                ('type_preuve', models.CharField(choices=[('RECU_ESPECES', 'Reçu espèces'), ('SIGNATURE_CLIENT', 'Signature client'), ('CAPTURE_PSP', 'Capture confirmation PSP'), ('JUSTIFICATIF_VIREMENT', 'Justificatif de virement'), ('JUSTIFICATIF_REMBOURSEMENT', 'Justificatif de remboursement'), ('AUTRE', 'Autre')], max_length=30)),
                ('commentaire', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='core.paiement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
