# Generated by Django 6.0.7 on 2026-09-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_telephone_e164'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='carte_dernier4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='paiement',
            name='carte_expiration',
            field=models.CharField(blank=True, default='', help_text='Format MM/AA, affichage uniquement.', max_length=5),
        ),
        migrations.AddField(
            model_name='paiement',
            name='carte_marque',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
