# Generated by Django 6.0.7 on 2026-09-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_paiement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_xof_facture',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Équivalent XOF réellement envoyé à PayDunya (celui-ci ne facture qu'en XOF), figé au moment de la conversion — cf. constants.convertir_vers_xof. Nul quand `devise` est déjà XOF (montant_total suffit alors) ; ne pas recalculer depuis TAUX_VERS_XOF pour un remboursement, ce taux peut changer.", max_digits=12, null=True),
        ),
    ]
