# Generated by Django 6.0.7 on 2026-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_paiement_montant_xof_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contrat_transporteur_accepte_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contrat_transporteur_version_acceptee',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
