# Generated by Django 6.0.7 on 2026-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_contrat_transporteur_accepte_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='mobile_numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mobile_operateur',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
