from django.urls import path
from .views import *


urlpatterns = [

    path('', api_root, name='api-root'),
    path('register/',UserCreateView.as_view(),name='register'),
    path('camions/',CamionListCreateView.as_view(),name='camions' ),
    path('camions/<int:pk>/',CamionDetailView.as_view(),name='camion-detail'),
    path('camions/images/', ImageCamionCreateView.as_view(), name='camions-images'),
    path('camions/images/<int:pk>/', ImageCamionDetailView.as_view(), name='camions-images-detail'),
    path('chauffeurs/', ChauffeurListCreateView.as_view(), name='chauffeurs'),
    path('chauffeurs/<int:id>/', ChauffeurDetailView.as_view(), name='chauffeur-detail'),
    path('affectations/', AffectationChauffeurListCreateView.as_view(), name='affectations'),
    path('affectations/<int:id>/terminer/', terminer_affectation, name='affectation-terminer'),
    path('demandes/',DemandeTransportListCreateView.as_view(),name="demandes"),
    path('demandes/<int:pk>/',DemandeDetailView.as_view(),name="demande-detail"),
    path('missions/create/',MissionCreateView.as_view(),name="missions-create"),
    path('missions/<int:id>/accepter/',accepter_mission),
    path('missions/<int:id>/refuser/',refuser_mission),
    path('missions/<int:id>/terminer/',terminer_mission),
    path('dashboard/',dashboard,name="dashboard"),
    path('recherche-camions/',RechercheCamionView.as_view(),name="recherche-camions"),
    path('transporteur/flotte-positions/',FlottePositionsView.as_view(),name="flotte-positions"),
    path('profil/',profil,name="profil"),
    path('profil/mot-de-passe/',changer_mot_de_passe,name="profil-mot-de-passe"),
    path('mot-de-passe-oublie/',demander_reinitialisation,name="mot-de-passe-oublie"),
    path('mot-de-passe-oublie/confirmer/',confirmer_reinitialisation,name="mot-de-passe-oublie-confirmer"),
    path('propositions/',PropositionListCreateView.as_view()),
    path('propositions/<int:id>/accepter/',accepter_proposition),
    path('propositions/<int:id>/refuser/',refuser_proposition),
    path('missions/',MissionListView.as_view(),name="missions"),
    path("tracking/",PositionGPSCreateView.as_view()),
    path("tracking/<int:mission_camion_id>/historique/",historique_positions,name="tracking-historique"),
    path("chauffeur/login/",ChauffeurLoginView.as_view()),
    path("chauffeur/<int:chauffeur_id>/missions/",ChauffeurMissionsView.as_view()),
    path("chauffeur/<int:chauffeur_id>/missions/<int:mission_id>/demarrer/",chauffeur_demarrer_mission),
    path("chauffeur/<int:chauffeur_id>/missions/<int:mission_id>/terminer/",chauffeur_terminer_mission),
    path("chauffeur/<int:chauffeur_id>/position/",ChauffeurPositionView.as_view()),
    path("chauffeur/<int:chauffeur_id>/photo/",ChauffeurPhotoView.as_view()),
    path("transporteur/dashboard/",TransporteurDashboardView.as_view()),
    path("client/dashboard/",ClientDashboardView.as_view()),
    path("admin/dashboard/",AdminDashboardView.as_view()),
    path("notifications/",NotificationListView.as_view(),name="notifications"),
    path("notifications/<int:id>/lire/",marquer_notification_lue,name="notification-lire"),
    path("notifications/lire-toutes/",marquer_toutes_notifications_lues,name="notifications-lire-toutes"),

    path("missions/<int:mission_id>/paiement/",detail_paiement_mission,name="paiement-detail-mission"),
    path("missions/<int:mission_id>/paiement/initier/",initier_paiement,name="paiement-initier"),
    path("paiements/moyens/",moyens_paiement,name="paiement-moyens"),
    path("payment/ipn/", paiement_ipn, name="payment-ipn"),
    path("paiements/webhook/",paiement_webhook,name="paiement-webhook"),
    path("paiements/retour/",paiement_retour,name="paiement-retour"),
    path("paiements/annule/",paiement_annule,name="paiement-annule"),
    path("paiements/<int:id>/confirmer-carte/",confirmer_paiement_carte,name="paiement-confirmer-carte"),
    path("paiements/<int:id>/encaisser-manuel/",encaisser_paiement_manuel,name="paiement-encaisser-manuel"),
    path("paiements/<int:id>/valider/",valider_paiement_manuel,name="paiement-valider"),
    path("paiements/<int:id>/verser/",verser_paiement,name="paiement-verser"),
    path("paiements/<int:id>/rembourser/",rembourser_paiement_endpoint,name="paiement-rembourser"),
    path("paiements/<int:id>/litiges/",ouvrir_litige,name="paiement-ouvrir-litige"),
    path("litiges/<int:id>/resoudre/",resoudre_litige,name="litige-resoudre"),
    path("mes-paiements/",MesPaiementsView.as_view(),name="mes-paiements"),
    path("agent/paiements-a-encaisser/",AgentPaiementsView.as_view(),name="agent-paiements"),
    path("admin/paiements/",AdminPaiementsView.as_view(),name="admin-paiements"),
    path("admin/litiges/",AdminLitigesView.as_view(),name="admin-litiges"),
    path("admin/utilisateurs/",AdminUtilisateursView.as_view(),name="admin-utilisateurs"),
    path("admin/chauffeurs/",AdminChauffeursView.as_view(),name="admin-chauffeurs"),
    path("admin/camions/",AdminCamionsView.as_view(),name="admin-camions"),
    path("admin/missions/",AdminMissionsView.as_view(),name="admin-missions"),
    path("admin/demandes/",AdminDemandesView.as_view(),name="admin-demandes"),

]
