"""
Django settings for AfriFlotte project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from decimal import Decimal
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

_SECRET_KEY_DEV_PAR_DEFAUT = (
    'django-insecure-6y!q8l8)3okl)+-p-6e_re!gta4i1uz*2u^ga7p$=z%k@g&-ae'
)

# SECURITY WARNING: keep the secret key used in production secret!
# En dev, la clé historique reste utilisée sans rien à configurer. En
# production (DEBUG=False), une vraie SECRET_KEY doit être fournie via
# l'environnement (Railway : Variables du service) — on refuse de démarrer
# avec la clé de dev par défaut plutôt que de servir du trafic réel avec un
# secret public sur GitHub.
SECRET_KEY = os.environ.get('SECRET_KEY', _SECRET_KEY_DEV_PAR_DEFAUT)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').strip().lower() in ('1', 'true', 'yes')

if not DEBUG and SECRET_KEY == _SECRET_KEY_DEV_PAR_DEFAUT:
    raise ImproperlyConfigured(
        "SECRET_KEY doit être définie via une variable d'environnement "
        "quand DEBUG=False (settings.py conserve la clé de dev par défaut "
        "uniquement pour que `manage.py runserver` fonctionne sans config)."
    )

# Hôtes autorisés à servir des requêtes (obligatoire dès DEBUG=False) :
# liste séparée par des virgules dans la variable d'environnement
# ALLOWED_HOSTS (ex: "web-production-xxxx.up.railway.app,afriflotte.com") —
# À DÉFINIR EXPLICITEMENT SUR RAILWAY, ne pas compter uniquement sur
# RAILWAY_PUBLIC_DOMAIN ci-dessous : en pratique cette variable ne s'est pas
# résolue lors du premier déploiement (2026-09-03, "DisallowedHost" sur tout
# le site), donc son ajout automatique n'est qu'un bonus best-effort, pas une
# garantie.
ALLOWED_HOSTS = [
    hote.strip()
    for hote in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if hote.strip()
]
_domaine_railway = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _domaine_railway and _domaine_railway not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_domaine_railway)
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'corsheaders',
    'core',
    'vitrine',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Sert STATIC_URL (admin, assets de la vitrine) directement depuis
    # Gunicorn, compressé + avec des en-têtes de cache — pas besoin d'un CDN
    # séparé pour démarrer sur Railway. Juste après SecurityMiddleware, avant
    # tout le reste, comme documenté par WhiteNoise.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AfriFlotte.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AfriFlotte.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Sans DATABASE_URL (dev local) : SQLite inchangé, zéro config nécessaire.
# Avec DATABASE_URL (Railway : ajoutée automatiquement dès qu'un plugin
# PostgreSQL est attaché au service Django) : PostgreSQL, web ET APK partagent
# alors la même base via la même API.
_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# En dev, le hasher PBKDF2 par défaut de Django (1.2M itérations) peut à lui
# seul prendre plusieurs secondes de CPU par connexion sur du matériel
# modeste — au point de dépasser le timeout côté app et de faire échouer des
# connexions pourtant valides. `FastDebugPBKDF2Hasher` (core/hashers.py) est
# gardé en tête de liste uniquement si DEBUG=True ; les hashers Django
# standard restent listés ensuite pour continuer à vérifier les mots de
# passe déjà hachés à l'ancien coût. Ne jamais activer ce hasher rapide hors
# DEBUG.
if DEBUG:
    PASSWORD_HASHERS = [
        'core.hashers.FastDebugPBKDF2Hasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
        'django.contrib.auth.hashers.Argon2PasswordHasher',
        'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
        'django.contrib.auth.hashers.ScryptPasswordHasher',
    ]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# CSRF ne concerne pas les appels API du site/APK (authentification par JWT
# en en-tête `Authorization`, pas par cookie de session) — seul le formulaire
# HTML de connexion `/admin/` en dépend. Obligatoire dès DEBUG=False dès que
# l'admin est servi sur autre chose que localhost. Même source que
# ALLOWED_HOSTS, préfixée en https:// comme l'exige Django.
CSRF_TRUSTED_ORIGINS = [f'https://{hote}' for hote in ALLOWED_HOSTS]

# Railway termine le HTTPS à son proxy et transmet à Gunicorn en HTTP simple
# avec cet en-tête — sans ça, SECURE_SSL_REDIRECT provoquerait une boucle de
# redirection infinie (Django croirait chaque requête non chiffrée).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Valeur volontairement modeste (1h) plutôt que le 1 an habituellement
    # recommandé : HSTS mal réglé peut rendre un domaine injoignable en HTTP
    # pendant toute sa durée si le HTTPS a un problème (Django lui-même met
    # en garde dessus) — à augmenter une fois le HTTPS confirmé stable en
    # production, pas avant.
    SECURE_HSTS_SECONDS = 3600

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Destination de `collectstatic` (exécuté au déploiement, voir Procfile) —
# c'est ce dossier que WhiteNoise sert ensuite. Inutile en dev (`runserver`
# sert les fichiers statiques lui-même sans collectstatic).
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# ATTENTION déploiement : ce dossier vit sur le disque du conteneur Railway,
# qui n'est PAS persistant entre deux déploiements (redeploy = disque neuf).
# Les photos de camions/preuves de paiement déjà uploadées seraient donc
# perdues à chaque redéploiement tant qu'un Volume Railway n'est pas monté
# ici (ou tant que le stockage ne migre pas vers S3/Cloudinary) — non traité
# dans cette préparation, à décider séparément (cf. rapport de fin de tâche).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # BrowsableAPIRenderer expose une UI HTML explorable sur chaque endpoint
    # (pratique en dev) — inutile pour les vrais clients (JSON only) et
    # superflu à exposer publiquement en production.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ]

}

# Session "façon Facebook" : rester connecté indéfiniment tant que l'app est
# rouverte au moins une fois par fenêtre de ROTATE_REFRESH_TOKENS, jusqu'à
# déconnexion explicite. Sans ça, le défaut SimpleJWT (refresh token de 1
# jour, jamais renouvelé) déconnectait tout utilisateur n'ayant pas rouvert
# l'app depuis plus de 24h. ACCESS_TOKEN_LIFETIME reste au défaut (5 min) —
# c'est déjà couvert côté Flutter par TokenRefreshScheduler/AuthenticatedHttp,
# pas la peine de l'allonger. ROTATE_REFRESH_TOKENS=True fait qu'un nouveau
# refresh token (avec une échéance repoussée) est émis à chaque rafraîchissement
# — voir `ApiService.refreshAccessToken` côté Flutter, qui doit stocker ce
# nouveau refresh token, pas seulement le nouvel access token.
SIMPLE_JWT = {
    'REFRESH_TOKEN_LIFETIME': timedelta(days=180),
    'ROTATE_REFRESH_TOKENS': True,

}

# ==========================
# PAIEMENTS
# ==========================
#
# Commission plateforme prélevée sur chaque paiement (cf. core/services.py,
# calculer_commission). Centralisée ici plutôt qu'en dur dans services.py
# pour pouvoir l'ajuster sans toucher au code métier.
COMMISSION_AFRIFLOTTE_SEUIL = Decimal(os.environ.get('COMMISSION_AFRIFLOTTE_SEUIL', '3000000'))
COMMISSION_AFRIFLOTTE_TAUX = Decimal(os.environ.get('COMMISSION_AFRIFLOTTE_TAUX', '5.00'))
COMMISSION_AFRIFLOTTE_TAUX_SUPERIEUR = Decimal(os.environ.get('COMMISSION_AFRIFLOTTE_TAUX_SUPERIEUR', '4.00'))

# PAIEMENT_GATEWAY reste sur "simulateur" (core/gateway_paiement.py) tant que
# les clés PayDunya ci-dessous ne sont pas renseignées — passer à "paydunya"
# active le vrai prestataire. Contrairement à SECRET_KEY ci-dessus (en dur,
# préexistant, hors périmètre), les secrets de paiement passent par l'env dès
# leur introduction : ce sont des identifiants d'argent réel.
PAIEMENT_GATEWAY = os.environ.get('PAIEMENT_GATEWAY', 'simulateur')

# PayDunya, disponible dans toute la CEDEAO — voir
# core/gateway_paiement.py:PayDunyaGatewayAdapter (conversion XOF pour les
# pays à devise propre) et core/constants.py:PAYDUNYA_MOBILE_MONEY_PAR_PAYS
# (Mobile Money limité aux pays où PayDunya l'opère). Les 4 clés viennent du
# tableau de bord PayDunya (mode test = préfixe "test_" sur les clés privée/
# publique). PAYDUNYA_MODE="test" (par défaut) utilise l'API sandbox,
# "live" l'API réelle.
PAYDUNYA_MASTER_KEY = os.environ.get('PAYDUNYA_MASTER_KEY', '')
PAYDUNYA_PRIVATE_KEY = os.environ.get('PAYDUNYA_PRIVATE_KEY', '')
PAYDUNYA_PUBLIC_KEY = os.environ.get('PAYDUNYA_PUBLIC_KEY', '')
PAYDUNYA_TOKEN = os.environ.get('PAYDUNYA_TOKEN', '')
PAYDUNYA_MODE = os.environ.get('PAYDUNYA_MODE', 'test')

# URL publique de ce serveur Django, utilisée pour construire les URL de
# callback/retour/annulation envoyées à PayDunya (doit être une vraie URL
# HTTPS accessible depuis Internet en production — PayDunya ne peut pas
# atteindre 127.0.0.1 pour son IPN).
PAIEMENT_RETOUR_BASE_URL = os.environ.get(
    'PAIEMENT_RETOUR_BASE_URL', 'http://127.0.0.1:8000'
)


# ==========================
# EMAIL (réinitialisation de mot de passe)
# ==========================
#
# La réinitialisation de mot de passe (core/services.py:
# envoyer_email_reinitialisation) est le seul usage actuel de l'email dans
# l'app — pas de compte SMS/passerelle disponible pour ce canal (cf.
# historique de core/views.py:demander_reinitialisation).
#
# En dev (DEBUG=True) : les emails s'affichent dans la console au lieu
# d'être réellement envoyés — aucune configuration n'est nécessaire pour
# tester le flux localement. En production, un vrai serveur SMTP DOIT être
# configuré via les variables d'environnement ci-dessous (Railway :
# Variables du service) ; tant qu'EMAIL_HOST_PASSWORD est vide, l'envoi
# échouera (loggé, cf. envoyer_email_reinitialisation, jamais une 500 pour
# l'utilisateur) sans qu'aucun code ne parte réellement.
EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
    if DEBUG else
    'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').strip().lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'AfriFlotte <no-reply@afriflotte.com>')


# ==========================
# SITE VITRINE
# ==========================
#
# URL vers laquelle la vitrine (app `vitrine`, servie à la racine du domaine)
# renvoie les boutons "Se connecter"/"Créer un compte" — l'app Flutter Web
# elle-même, servie à part (chemin ou sous-domaine séparé selon le
# déploiement retenu). Racine "/" reste occupée par la vitrine, jamais par
# l'app : voir vitrine/views.py.
FLUTTER_APP_URL = os.environ.get('FLUTTER_APP_URL', '/app/')
